const GameConfig = {
    GAME_WIDTH: 480,
    GAME_HEIGHT: 800,

    MAX_LIVES: 5,
    HIT_IMMUNITY_MS: 1000,

    SWAP_MAX_STACK: 3,
    SWAP_CHARGE_INTERVAL_MS: 5000,

    WEAPON_SLOTS_PER_CHARACTER: 4,

    PLAYER_SIZE: 24,
    PLAYER_SPEED: 260,
    PLAYER_FIRE_INTERVAL_MS: 250,

    PLAYER_BULLET_WIDTH: 6,
    PLAYER_BULLET_HEIGHT: 14,
    PLAYER_BULLET_SPEED: 520,
    PLAYER_BULLET_COLOR: 0xffee88,

    ENEMY_BULLET_RADIUS: 6,
    ENEMY_BULLET_SPEED: 220,
    ENEMY_BULLET_COLOR: 0xff7744,
    ENEMY_FIRE_INTERVAL_MS: 500,

    PLAYER_1_COLOR: 0xff4466,
    PLAYER_2_COLOR: 0x4488ff,
    INVINCIBLE_STROKE_COLOR: 0xffee00,
    INVINCIBLE_STROKE_WIDTH: 3,
};
